name: Generate Data (singular or plural based on your data)
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Add steps to update your data here (e.g., fetch, transform, generate)
      # ...

      # Snake Animation (optional, comment out if not needed)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: msabhilash1996
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
